# pypopRF configuration file
#
# Configuration options:
#   work_dir: Root directory for project
#   data_dir: Directory containing input files
#   covariates: Dictionary of covariate raster files
#   mastergrid: Path to mastergrid file
#   census_data: Path to census data file
#   census_pop_column: Population column in census data
#   census_id_column: ID column in census data
#   output_dir: Directory for output files
#   block_size: Processing block size [width, height]
#   max_workers: Number of parallel workers
#   show_progress: Whether to show progress bars
#
# Example covariates:
#   covariates:
#     key1: "path/to/raster1.tif"
#     key2: "path/to/raster2.tif"
#
work_dir: .
data_dir: data
covariates:
  cnt: test_buildingCount.tif
  srf: test_buildingSurface.tif
  vol: test_buildingVolume.tif
mastergrid: test_mastergrid.tif
census_data: test_admin3.csv
census_pop_column: pop
census_id_column: id
output_dir: output
block_size:
- 512
- 512
max_workers: 8
show_progress: true
